defaults:
  - generator: null

# Generate GAN-generated images on-the-fly during training 
load_from_disk: False

# Validation set size
val_images: 256

# Training options
iters_per_epoch: 2000

# GAN Dataset
device: 'cuda'  # device for generator
model_type: "fixed"
model_light_checkpoint: null  # model checkpoint (e.g. .../latest.pth)
model_dark_checkpoint: null  # model checkpoint (e.g. .../latest.pth)
zs: null
kwargs:
  z_noise: 0.0
  z_noise_truncation: 1.0
  r_light: 5.0
  r_dark: 5.0
  filter_cc_threshold_light: 0.2
  filter_cc_threshold_dark: 0.2
  filter_size_thresholds_light: [0.0, 0.5]
  filter_size_thresholds_dark: [0.0, 0.5]
  filter_histogram_bins_light: 12
  filter_histogram_bins_dark: 12
  filter_roundness_threshold_light: 0.0
  filter_roundness_threshold_dark: 0.0
  filter_overlap_threshold: 0.0
  batch_size: 95
  generation_batch_size: 95

# Options generating dataset and saving to disk 
save_dir: null
save_size: 1000000
offset: 0