# @package _global_
defaults:
  - data_gen/generator: ???

hydra:
  run:
    dir: ./outputs/optimization/${model_type}-${data_gen.generator.gan_type}-${name}/${now:%Y-%m-%d_%H-%M-%S}

# Basic config
name: default
seed: 42

# Data
batch_size: 32

# Model that transforms the latent variable z
model_type: fixed

# Optimizer
optimizer:
  cls: Adam
  kwargs:
    lr: 5e-3

# Scheduler
scheduler:
  cls: MultiStepLR
  iterations: 300
  kwargs:
    milestones: []
    gamma: 0.1

# Logging
log_every: 50
vis_every: 50

# During training, the shift radius `r` is sampled from a 
# normal distribution with these parameters
r:
  mean: 2.0
  var: 0.5
  min: 0.1

# Losses
losses:
  outside_circle_loss: 2.0
  sobel_shift_loss: 10.0
